apiVersion: apps/v1
kind: Deployment
metadata:
  name: serg046-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serg046-app-deployment
  template:
    metadata:
      labels:
        app: serg046-app-deployment
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: ghcr.io/serg046/serg046.dev/serg046-app:latest
        ports:
        - containerPort: 8080
