apiVersion: apps/v1
kind: Deployment
metadata:
  name: serg046-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serg046-app
  template:
    metadata:
      labels:
        app: serg046-app
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        command: ["/app/start.sh"]
        ports:
        - containerPort: 8000
