apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serg046-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - serg046.dev
    secretName: tls-secret
  rules:
  - host: *
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serg046-app-service
            port:
              number: 80
