apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serg046-app
spec:
  rules:
  - http:
      paths:
      - path: /ping
        pathType: Prefix
        backend:
          service:
            name: serg046-app
            port:
              number: 80
