name: Production Deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Inject GH secret
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "Server/appsettings.json"
          find: '"GitHubToken": ""'
          replace: '"GitHubToken": "${{ secrets.GIT_HUB_TOKEN }}"'
          regex: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Serg046
          password: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/serg046/serg046.dev/serg046-app:test
          platforms: linux/arm64
          push: true
    
      - name: Create kube config
        run: |
          KUBECONFIG=$(mktemp -d)/config
          base64 -d <(printf "%s" $KUBE_CONFIG_BASE64_DATA) > $KUBECONFIG
          echo KUBECONFIG=$KUBECONFIG >> $GITHUB_ENV
        env:
          KUBE_CONFIG_BASE64_DATA: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}

      - name: Install werf
        uses: werf/actions/install@v2
      
      - name: Run werf converge
        run: |
          . $(werf ci-env github --as-file) 
          werf converge --platform linux/arm64 --dev --verbose
        env:
          WERF_ENV: production

      - name: Run script
        run: |
          cat Server/appsettings.json
