name: Production Deployment
on:
  push:
    branches: [master]
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: ls
        run: ls Server
          
      - name: Inject GH secret
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        run: perl -pi -e 's/\"GitHubToken\"\:\s\"\"/\"GitHubToken\"\:\s\"$ENV{GIT_HUB_TOKEN}\"/' Server/appsettings.json
        
      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: development
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SET_ENV_URL: "envUrl=serg046.dev"
