name: Production Deployment
on:
  push:
    branches: [master]
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: ls
        run: ls Server
          
      - name: Inject GH secret
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        run: perl -pi -e 's/\"GitHubToken\"\:\s\"\"/\"GitHubToken\"\:\s\"$ENV{GIT_HUB_TOKEN}\"/' Server/appsettings.json
         
      - name: Install werf CLI  
        uses: werf/actions/install@v1.2
    
      - name: Create kube config
        run: |
          KUBECONFIG=$(mktemp -d)/config
          base64 -d <(printf "%s" $KUBE_CONFIG_BASE64_DATA) > $KUBECONFIG
          echo KUBECONFIG=$KUBECONFIG >> $GITHUB_ENV
        env:
          KUBE_CONFIG_BASE64_DATA: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
  
      - name: Run werf commands
        run: |
          source $(werf ci-env github --as-file)
          werf render --dev
          werf converge --dev
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WERF_ENV: production
